encoding:       utf-8
markdown:       redcarpet
permalink:      pretty
baseurl: /vimconf

gems:
  - jekyll-sitemap

redcarpet:
  extensions:
    - 'autolink'
    - 'tables'
    - 'strikethrough'

sass:
  # commented out while under development.
  #style: compressed
